
###################
# Perse Workspace
###################

[workspace]
resolver = "2"
members = [
  "perse_core",
  "perse_controller",
  "perse_data",
  "perse_view",
]

[workspace.package]
version = "0.1.11"

[workspace.dependencies]
##########################
### Perse `dependencies`
##########################
perse = { path = "./perse_core", version = "=0.1.9" }
perse_controller = { path = "./perse_controller", version = "=0.1.4" }
perse_data = { path = "./perse_data", version = "=0.1.1" }
perse_view = { path = "./perse_view", version = "=0.1.1" }

###########################
### Leptos `dependencies`
###########################
leptos = { version = "=0.5.0-rc3", features = ["nightly"] }
leptos_meta = { version = "=0.5.0-rc3", features = ["nightly"] }
leptos_actix = { version = "=0.5.0-rc3" }
leptos_router = { version = "=0.5.0-rc3", features = ["nightly"] }
http = { version = "=0.2" }
cfg-if = { version = "=1" }

##########################
### Leptos Configuration
##########################
[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.metadata.cargo-all-features]
denylist = ["actix-files", "actix-web", "leptos_actix"]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]
