
###################
# Perse Workspace
###################
[workspace]
resolver = "2"
members = [
  "perse_core",
  "perse_data",
]

[workspace.package]
version = "0.1.6"


[workspace.dependencies]
##########################
### Perse `dependencies`
##########################
perse = { path = "./perse_core", version = "=0.1.6" }
perse_data = { path = "./perse_data", version = "=0.1.6" }

###########################
### Leptos `dependencies`
###########################
cfg-if = { version = "=1" }


##########################
### Leptos Configuration
##########################

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[workspace.metadata.cargo-all-features]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]
