
##############
# Perse View
##############

[package]
name = "perse_view"
version = "0.1.0"
edition = "2021"
authors = ["Alex Watson <hello@perse.dev>"]
repository = "https://github.com/alexwatever/perse"
readme = "../README.md"
license = "MPL-2.0"

[dependencies]
leptos = { workspace = true }
leptos_actix = { workspace = true, optional = true }
http = { workspace = true, optional = true }

[features]
hydrate = [
  "leptos/hydrate",
]
ssr = [
  "leptos/ssr",
  "leptos_actix",
  "dep:http",
]
csr = [
  "leptos/csr",
]
