
##############
# Perse View
##############

[package]
name = "perse_view"
version = "0.1.4"
readme.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
leptos = { workspace = true }
leptos_actix = { workspace = true, optional = true }
leptos_router = { workspace = true }
actix-web = { workspace = true, optional = true }
http = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
serde = { version = "1.0.203" }
serde_json = { version = "1.0.117" }
# set to v0.3.64 to avoid conflicts
web-sys = { version = "=0.3.64" }

[features]
hydrate = [
  "leptos/hydrate",
]
ssr = [
  "leptos/ssr",
  "leptos_actix",
  "dep:actix-web",
  "dep:http",
]
csr = [
  "leptos/csr",
]
