
##############
# Perse View
##############

[package]
name = "perse_view"
version = "0.1.4"
readme.workspace = true
description.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
actix-web = { workspace = true, optional = true }
http = { workspace = true, optional = true }
leptos = { workspace = true }
leptos_actix = { workspace = true, optional = true }
leptos_router = { workspace = true, optional = true }

[features]
hydrate = [
  "leptos/hydrate",
]
ssr = [
  "leptos/ssr",
  "leptos_actix",
  "leptos_router",
  "actix-web",
  "dep:http",
]
csr = [
  "leptos/csr",
]
