
####################
# Perse Controller
####################

[package]
name = "perse_controller"
version = "0.1.8"
edition = "2021"
authors = ["Alex Watson <hello@perse.dev>"]
repository = "https://github.com/alexwatever/perse"
readme = "../README.md"
license = "MPL-2.0"

[dependencies]
leptos = { version = "=0.5.0-rc3", features = ["nightly"] }
leptos_meta = { version = "=0.5.0-rc3", features = ["nightly"] }
leptos_actix = { version = "=0.5.0-rc3", optional = true }
leptos_router = { version = "=0.5.0-rc3", features = ["nightly"] }
http = { version = "=0.2", optional = true }

[features]
ssr = [
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptos_actix",
  "dep:http",
]
csr = [
  "leptos/csr",
  "leptos_meta/csr",
  "leptos_router/csr",
]
