
##############
# Perse Data
##############
[package]
name = "perse_data"
version = "0.1.7"
edition = "2021"
authors = ["Alex Watson <hello@perse.dev>"]
repository = "https://github.com/alexwatever/perse"
readme = "../README.md"
license = "MPL-2.0"


[dependencies]
##########################
### Perse `dependencies`
##########################
dotenv = { version = "=0.15.0", optional = true }
sqlx = { version = "=0.7.1", optional = true, features = [ "postgres", "runtime-tokio", "tls-native-tls", "macros", "uuid", "chrono", "bigdecimal", "json" ] }
once_cell = { version = "=1.18.0", optional = true }

###########################
### Leptos `dependencies`
###########################
cfg-if = { workspace = true }


[features]
ssr = [
  #################
  ### Perse `SSR`
  #################
  "dep:dotenv",
  "dep:sqlx",
  "dep:once_cell",
]
