
name: CICD

on:
  push:
    branches:
      - main

env:
  APP_NAME: perse
  DOCKER_TEST_TAG: perse:test
  DOCKER_LATEST_TAG: perse:latest

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: test-build-checkout
        uses: actions/checkout@v4

      - name: Test Docker Build
        id: test-build-docker-image
        run: |
          docker build -t ${{ env.DOCKER_TEST_TAG }} ${{ env.APP_NAME }}

  deploy_cratesio:
    needs: tests
    name: Release Crates.io Package Update
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout
        id: deploy-cratesio-checkout
        uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        id: deploy-cratesio-toolchain
        with:
          toolchain: nightly
          override: true

      - uses: katyo/publish-crates@v2
        id: deploy-cratesio-cratesio
        with:
          path: './${{ env.APP_NAME }}'
          registry-token: ${{ secrets.PERSE_CRATESIO_API_TOKEN }}

  deploy_persedev:
    needs: tests
    name: Deploy Perse.dev Application
    runs-on: ubuntu-latest
    environment: Production
    env:
      FLY_API_TOKEN: ${{ secrets.PERSE_FLY_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        id: deploy-persedev-checkout
        uses: actions/checkout@v4

      - name: Load action - SuperFly
        id: deploy-persedev-load-superfly
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: Deploy to Fly.io
        id: deploy-persedev-flyio
        run: |
          flyctl deploy ${{ env.APP_NAME }} --remote-only
