
name: Deploy Perse to Perse.dev and Crates.io

on:
  push:
    branches:
      - main

env:
  APP_NAME: perse
  DOCKER_TEST_TAG: perse:test
  DOCKER_LATEST_TAG: perse:latest

jobs:
  test_build:
    name: Test Builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: test-build-checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        id: test-build-docker-image
        run: |
          docker build -t ${{ env.DOCKER_TEST_TAG }} ${{ env.APP_NAME }}
      - name: Run Docker Image
        id: test-build-docker-run
        run: |
          docker run --rm ${{ env.DOCKER_TEST_TAG }} ${{ env.APP_NAME }}

  deploy_persedev:
    needs: test_build
    name: Deploy Perse.dev App
    runs-on: ubuntu-latest
    environment: Production
    env:
      FLY_API_TOKEN: ${{ secrets.PERSE_FLY_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        id: deploy-persedev-checkout
        uses: actions/checkout@v3

      - name: Load action - SuperFly
        id: deploy-persedev-load-superfly
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: Deploy to Fly.io
        id: deploy-persedev-flyio
        run: |
          flyctl deploy ${{ env.APP_NAME }} --remote-only
